---
# name: jomrr.libvirtd
# file: tasks/main.yml

- name: "Install libvirtd packages"
  become: true
  ansible.builtin.package:
    name: "{{ _libvirtd_packages }}"
    state: present

- name: "Start and enable libvirtd service"
  become: true
  ansible.builtin.service:
    name: "{{ _libvirtd_service }}"
    state: started
    enabled: true
